name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1

      - uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0
        with:
          cache: true
          require-lockfile: true

      - name: Typecheck
        run: pnpm run typecheck

      - name: Lint
        run: pnpm run lint && pnpm run lint:plugin

      - name: Test
        run: pnpm run test

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1

      - uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0
        with:
          cache: true
          require-lockfile: true

      - name: Security Audit
        run: pnpm audit --audit-level=high
        continue-on-error: true
